# shutil.rmtree(pathlib.Path('my_directory_to_delete'))

# https://www.youtube.com/watch?v=2vxvSMkm5Lg&list=PLmWYh0f8jKSgv9FHydAWn9ZEdGmx0Ix_O
# podman build --format=docker --build-arg NAME="amazing" --build-arg TAG="2.426.2-jdk17" -f ./container_stuff/Dockerfile.jenkinsBlueOcean_centos -t my_image:latest ./container_stuff/

ARG TAG

FROM jenkins/jenkins:${TAG}

ARG NAME

# ENV NAME=$NAME
RUN echo "${NAME}"

RUN echo $NAME
LABEL key="wow I just wanna ${TAG}"

USER root

# RUN apt-get update && apt-get install -y lsb-release
# RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
#   https://download.docker.com/linux/debian/gpg
# RUN echo "deb [arch=$(dpkg --print-architecture) \
#   signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
#   https://download.docker.com/linux/debian \
#   $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
# RUN apt-get update && apt-get install -y docker-ce-cli
# RUN chown -R 1000:1000 "$JENKINS_HOME"

# USER jenkins
COPY start_my_image_${NAME}.txt start_my_image_${NAME}.txt

CMD ["/bin/bash", "-c", "echo ${NAME}"]

# RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"